[theme]
name = "modern"

[icons]
name = "awesome6"

[[block]]
block = "sound"
device = "hw:2,0"
format = "{volume}"
[block.theme_overrides]
idle_bg = "#f34c53"
info_bg = "#f34c53"
info_fg = "#282a36"
idle_fg = "#282a36"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"
[block.theme_overrides]
idle_bg = "#009784"
idle_fg = "#282a36"

[[block]]
block = "nvidia_gpu"
label = "RTX 3060"
show_temperature = false
show_memory = false
[block.theme_overrides]
idle_bg = "#f34c53"
idle_fg = "#282a36"

[[block]]
block = "time"
format = "%H:%M, %d %b"
timezone = "Europe/Lisbon"
interval = 60
[block.theme_overrides]
idle_bg = "#009784"
idle_fg = "#282a36"
