[theme]
name = "space-villain"
[theme.overrides]
good_bg = "#631261"
idle_bg = "#194b92"

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{signal_strength} @ {ssid}"
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "time"
format = "%H:%M, %d %b"
timezone = "Europe/Lisbon"
interval = 60
