[theme]
theme = "space-villain"
[theme.overrides]
good_bg = "#631261"
idle_bg = "#194b92"

[icons]
icons = "awesome6"

[[block]]
block = "net"
device = "wlan0"
interval = 5
format = " $icon $signal_strength @ $ssid "

[[block]]
block = "battery"
interval = 10

[[block]]
block = "time"
timezone = "Europe/Lisbon"
interval = 60

[[block]]
block = "sound"
device = "hw:2,0"
format = " $icon $volume "
[block.theme_overrides]
idle_bg = "#021d3b"

