[theme]
theme = "modern"

[icons]
icons = "awesome6"

[[block]]
block = "sound"
device = "hw:2,0"
format = "$icon $volume "
[block.theme_overrides]
idle_bg = "#459544"
info_bg = "#459544"
info_fg = "#282a36"
idle_fg = "#282a36"

[[block]]
block = "cpu"
interval = 1
format = "$icon i7 @$utilization "
[block.theme_overrides]
idle_bg = "#009784"
idle_fg = "#282a36"

[[block]]
block = "nvidia_gpu"
format = "$icon RTX 3060 @$utilization "
[block.theme_overrides]
idle_bg = "#459544"
idle_fg = "#282a36"

[[block]]
block = "time"
timezone = "Europe/Lisbon"
interval = 60
[block.theme_overrides]
idle_bg = "#009784"
idle_fg = "#282a36"
