[theme]
name = "space-villain"
[theme.overrides]
good_bg = "#631261"
idle_bg = "#194b92"

[icons]
name = "awesome6"

[[block]]
block = "time"
format = "%H:%M, %d %b"
timezone = "Europe/Lisbon"
interval = 60
