[theme]
name = "space-villain"

[icons]
name = "awesome6"

[[block]]
block = "music"
player = "spotify"
max_width = 25
dynamic_width = true
format = "{title} by {artist} "
marquee_interval = 0
marquee_speed = 0.3
on_click = "spotify"
on_collapsed_click = "spotify"
[block.theme_overrides]
info_bg = "#631261"
idle_bg = "#631261"

[[block]]
block = "sound"
device = "hw:2,0"
format = "{volume}"
[block.theme_overrides]
info_bg = "#194b92"
idle_bg = "#194b92"

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"
[block.theme_overrides]
idle_bg = "#631261"

[[block]]
block = "nvidia_gpu"
label = "RTX 3060"
show_temperature = false
show_memory = false
[block.theme_overrides]
idle_bg = "#194b92"

[[block]]
block = "speedtest"
interval = 1800
format = "{ping}{speed_down}"
[block.theme_overrides]
idle_bg = "#631261"

[[block]]
block = "time"
format = "%H:%M, %d %b"
timezone = "Europe/Lisbon"
interval = 60
[block.theme_overrides]
idle_bg = "#194b92"
